trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: emmanuelbenitez/Be.Stateless.Build.Agent.Yaml.Pipeline.Templates
      endpoint: emmanuelbenitez

extends:
    template: Pipelines/pwsh/continuous-integration.yml@templates
    parameters:
        Major: 2
        Minor: 0
        SkipTest: false
